export const TASK_CENTER_COPY = {
  missingProjectId: "缺少 projectId",
  loading: "加载中...",
  processing: "处理中...",
  allOption: "全部",
  refresh: "刷新",
  requestIdCopyTitle: "复制失败：请手动复制请求 ID（request_id）",
  runIdCopyTitle: "复制失败：请手动复制 run_id",
  copyDebugInfoTitle: "复制失败：请手动复制排障信息",
  cancelQueuedProjectTaskConfirm: "确认取消该排队中的任务？取消后将不会执行。",
  cancelBatchConfirm: "确认取消当前批处理任务？取消后本批不会继续执行。",
  unknownErrorType: "ERROR",
  unknownErrorMessage: "未知错误",

  queueStatusAria: "队列状态 (taskcenter_queue_status)",
  queueBackendLabel: "配置后端（queue_backend）",
  effectiveBackendLabel: "实际后端（effective_backend）",
  redisOkLabel: "redis_ok",
  queueNameLabel: "queue",
  queueInlineWarning: "提示：inline 为进程内单线程 worker，任务会排队串行执行；如需并发请启动 rq+worker。",
  queueHealthCopyButton: "复制 health 请求 ID（request_id）",

  usageLinksPrefix: "常用入口：",
  helpStructuredMemory: "连续性底座",
  helpWriting: "写作页",
  helpUsageSuffix: "之间来回跳转，查看“提议→应用→回滚”的全链路。",

  changeSetsSectionAria: "变更集 (taskcenter_changesets_section)",
  changeSetsTitle: "变更集",
  changeSetsHint: "按状态筛选；点击条目查看摘要与原始数据（默认折叠）",
  changeSetsStatusHint: "状态说明：未应用=仅提议 | 已应用=已落库 | 已回滚=已撤销 | 失败=执行异常",
  changeSetsEmpty: "暂无变更集",
  changeSetsStatusLabel: "状态",
  countLabels: {
    all: "总计",
    queued: "排队中",
    running: "运行中",
    done: "完成",
    failed: "失败",
  },
  changeSetsCounts: {
    all: "总计",
    proposed: "未应用",
    applied: "已应用",
    rolledBack: "已回滚",
    failed: "失败",
  },

  tasksSectionAria: "任务列表 (taskcenter_tasks_section)",
  tasksTitle: "后台任务",
  tasksHintPrefix: "失败任务会显示错误摘要与 ",
  tasksStatusHint: "状态说明：排队中→运行中→完成/失败（如失败可用 request_id 查后端日志）",
  tasksEmpty: "暂无任务",
  tasksFailedOnly: "仅看失败",

  projectTasksSectionAria: "项目任务 (taskcenter_projecttasks_section)",
  projectTasksTitle: "项目任务",
  projectTasksHint:
    "用于 worldbook/search/vector/graph 等自动化后台更新；点击条目查看详情（params/result/error 已脱敏）",
  projectTasksStatusHint: "状态说明：排队中→运行中→完成/失败",
  projectTasksLiveStatusPrefix: "Project SSE: ",
  projectTasksLiveLabels: {
    idle: "idle",
    connecting: "reconnecting",
    open: "connected",
    error: "fallback polling",
  },
  projectTasksEmpty: "暂无项目任务",
  projectTasksFailedOnly: "仅看失败",
  projectTasksRetry: "重试",
  projectTasksCancel: "取消",
  projectTasksRetryToast: "已重试任务",
  projectTasksCancelToast: "已取消任务",
  projectTasksIdempotencyPrefix: "幂等键：",

  detailCopyDebug: "复制 Debug 信息",
  detailClose: "关闭",
  detailOverview: "当前状态",
  detailActions: "下一步动作",
  detailGenerationRun: "写作运行记录",
  detailError: "失败与风险",
  detailChangeSet: "变更集落地",
  detailResults: "结果落点",
  detailRawJson: "原始数据（JSON）",
  detailNoError: "无错误信息",
  detailMissingChangeSet: "该任务结果里还没有变更集 ID（result.change_set），可能仍在运行或已经失败。",
  detailApplyRollbackHint: "提示：应用变更/回滚变更需要 editor 权限；失败时可复制 request_id 排障。",
  detailRefreshProjectTask: "刷新详情",
  detailApplyChangeSetToast: "已应用变更集",
  detailRollbackChangeSetToast: "已回滚变更集",

  requestIdCopyButton: "复制请求 ID（request_id）",
  projectTaskRunIdCopyButton: "复制 run_id",
  projectTaskRunIdOpenButton: "打开运行记录",
  applyChangeSetButton: "应用变更",
  rollbackChangeSetButton: "回滚变更",

  runtimeTitle: "运行现场",
  runtimeRefreshButton: "刷新现场",
  runtimeEmpty: "还没有拿到统一运行现场。",
  runtimeBatchTitle: "批处理现场",
  runtimeArtifactsTitle: "结果落点",
  runtimeTimelineTitle: "任务时间线",
  runtimeNoBatchItems: "还没有批处理条目。",
  runtimeNoTimeline: "还没有时间线事件。",
  runtimeOpenGenerationRun: "打开运行记录",
  runtimeBatchPause: "暂停批处理",
  runtimeBatchResume: "继续批处理",
  runtimeBatchRetryFailed: "重试失败章节",
  runtimeBatchSkipFailed: "跳过失败章节",
  runtimeBatchCancel: "取消批处理",
  runtimeBatchWorking: "处理中…",
  runtimeBatchPausedToast: "批处理已暂停。",
  runtimeBatchResumedToast: "批处理已继续。",
  runtimeBatchRetryFailedToast: "失败章节已加入重试。",
  runtimeBatchSkipFailedToast: "失败章节已跳过。",
  runtimeBatchCanceledToast: "批处理已取消。",
} as const;
